name : Map Generator 

on:
  workflow_dispatch:
  
jobs:
  env-setup:
    name: Run the scripts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Prepare environment
        run: |
          sudo apt install python3 -y
          sudo apt install python3-pip -y
          sudo apt-get update -y
          pip3 --version
          python3 --version
          pip3 install -r requirements.txt
          python3 start.py
      - name: Commit map
        run: |
          git config --local user.email "ipsitamishra16893@gmail.com"
            git config --local user.name "GitHub Action Committer"
            git add .
            git commit -m "Updated map"
      - name: Push map to master
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.HA_TOKEN }}
          force: true
        
    
